services:
  weather_server:
    build:
      context: .
      dockerfile: Dockerfile.weather
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - mcpnetwork

  math_server:
    build:
      context: .
      dockerfile: Dockerfile.math
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - mcpnetwork

  brave_server:
    build:
      context: .
      dockerfile: Dockerfile.brave
    ports:
      - "5002:5002"
    env_file:
      - .env
    networks:
      - mcpnetwork

networks:
  mcpnetwork:
    driver: bridge