FROM python:3.13-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install uv
RUN uv pip install --system -r pyproject.toml

COPY src/ ./src/
ENV PYTHONPATH=/app

EXPOSE 5003

CMD ["python", "src/servers/postgres_server.py"]
