services:
  mcpserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - mcpnetwork

networks:
  mcpnetwork:
    driver: bridge